### ISSUE TITLE
CI/CD wont work

### ISSUE THREAD

**Issue by HannesGitH** [HannesGitH/WhiteboardPRO#3]
node throws `illegal operation on a directory, open '/home/runner/work/WhiteboardPRO/WhiteboardPRO/Chrome-Extension`
although this folder exists

**Comment by eddyvalverde** [comment]
Error on GitHub Actions appear as EISDIR, which stands for "Error, Is Directory"
So, instead of a directory it should be a file after -x in the following line:
https://github.com/HannesGitH/WhiteboardPRO/blob/7b92bc9ec7f129083d3f5c50abdf967ae8287eb0/.github/workflows/create_release.yml#L30

source: [https://stackoverflow.com/questions/34959038/npm-stuck-giving-the-same-error-eisdir-illegal-operation-on-a-directory-read-a#:~:text=EISDIR%20stands%20for%20%22Error%2C%20Is,done%20the%20error%20is%20thrown.](url)

**Comment by HannesGitH** [comment]
thank you :) 
i thought the error came form the last bit `....PRO.pem Chrome-Extension/WhiteboardPRO ` which is and should be a DIR 
which totally confused me, i didnt even had the idea of the error not beeing at that exact location :D

So thanks again, that fixed it
